stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw
  data_preprocess:
    cmd: python src/data_preprocess.py
    deps:
    - data/raw
    - src/data_preprocess.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data/vectorized
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/vectorized
    - src/model_building.py
    params:
    - model_building.eval_metric
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - models/xgb_model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - data/vectorized
    - models/xgb_model.pkl
    metrics:
    - results/evaluation_metrics.json
